# Generated by Django 2.2.1 on 2019-05-05 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suit_num', models.PositiveIntegerField()),
                ('floor_num', models.PositiveIntegerField()),
                ('street_num', models.PositiveIntegerField()),
                ('city', models.TextField()),
                ('province', models.TextField()),
                ('country', models.TextField()),
                ('postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=6)),
                ('telephone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HoursOfOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('short_desc', models.TextField()),
                ('self_webpage_link', models.URLField()),
                ('price', models.PositiveIntegerField()),
                ('duration_in_mins', models.IntegerField(verbose_name=2)),
                ('duration_in_hours', models.IntegerField(verbose_name=4)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category')),
                ('main_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Image')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Image')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('short_desc', models.TextField()),
                ('long_desc', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Address')),
                ('contact_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ContactNumber')),
                ('logo_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_logo_image', to='service.Image')),
                ('web_page_logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_web_page_logo', to='service.Image')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Image')),
            ],
        ),
    ]
