# Generated by Django 2.2.1 on 2019-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
