# Generated by Django 2.2.1 on 2019-05-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_address_street_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursofoperation',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday'), ('All', 'All Days')], default='Mon', max_length=10),
        ),
    ]
