# Generated by Django 2.2.1 on 2019-05-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_hoursofoperation_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='contactnumber',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='hoursofoperation',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='aboutus/'),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor_num',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='address',
            name='suit_num',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo_image',
            field=models.ImageField(upload_to='brand/logo/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='web_page_logo',
            field=models.ImageField(upload_to='brand/tablogo/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_in_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_in_mins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='main_pic',
            field=models.ImageField(upload_to='service/thumb/'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='service/others/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
