# Generated by Django 2.2.1 on 2019-05-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20190505_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceimage',
            name='service',
        ),
    ]
