# Generated by Django 2.2.1 on 2019-05-05 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_serviceimage_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
    ]
