# Generated by Django 2.2.1 on 2019-05-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_serviceimage_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceimage',
            old_name='service',
            new_name='service_name',
        ),
    ]
