# Generated by Django 2.2.1 on 2019-05-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20190505_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='email',
            field=models.TextField(default='sourcilexpert@gmail.com'),
            preserve_default=False,
        ),
    ]
