# Generated by Django 2.2.1 on 2019-06-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_appointmentrequest_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryFileUpload',
            fields=[
                ('upload_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploaded/attachments/')),
            ],
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='sender_name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='file',
            field=models.FileField(default='a', upload_to='uploaded/attachments/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='images/aboutus/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo_image',
            field=models.ImageField(upload_to='images/brand_logo/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='web_page_logo',
            field=models.ImageField(upload_to='images/brand_web_page_logo/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='main_pic',
            field=models.ImageField(upload_to='images/service/thumb/'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='images/service/all/'),
        ),
    ]
