# Generated by Django 2.2.1 on 2019-06-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20190607_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='resume_pdf',
            field=models.FileField(default='asd', upload_to='uploaded/resume/'),
            preserve_default=False,
        ),
    ]
